services:
  mdp-client:
    build:
      context: ./client
      dockerfile: docker/Dockerfile.dev
    container_name: client-dev
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - ./client/.env
    environment:
      - VITE_NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - HOST=0.0.0.0
    stdin_open: true
    tty: true

  mdp-server:
    build:
      context: ./server
      dockerfile: docker/Dockerfile.dev
    container_name: server-dev
    command: npm run dev
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - ./server/.env
    environment:
      - NODE_ENV=development
    depends_on:
      - mdp-mongo

  mdp-socket:
    build:
      context: ./socket
      dockerfile: docker/Dockerfile.dev
    container_name: socket-dev
    command: npm run dev
    ports:
      - "4000:4000"
    volumes:
      - ./socket:/app
      - /app/node_modules
    env_file:
      - ./socket/.env
    environment:
      - NODE_ENV=development
    stdin_open: true
    tty: true

